apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciyex-ehr-ui
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ciyex-ehr-ui
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
