apiVersion: apps/v1
kind: Deployment
metadata:
  name: ciyex-ehr-ui
spec:
  template:
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: ciyex-ehr-ui
          env:
            - name: NODE_ENV
              value: "production"
            - name: NEXT_PUBLIC_ENV
              value: "production"
            - name: NEXT_PUBLIC_API_URL
              value: "https://api.ciyex.org"
            - name: NEXT_PUBLIC_KEYCLOAK_URL
              value: "https://aran.me"
            - name: NEXT_PUBLIC_KEYCLOAK_REALM
              value: "master"
            - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
              value: "ciyex-app"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
