apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: ciyex-ehr-ui
    count: 1

images:
  - name: registry.apps-prod.us-east.in.hinisoft.com/ciyex-ehr-ui
    newTag: "0.0.1-rc"

configMapGenerator:
  - name: ehr-ui-config
    literals:
      - NODE_ENV=staging
      - NEXT_PUBLIC_ENV=staging
      - NEXT_PUBLIC_API_URL=https://api-stage.ciyex.org
      - NEXT_PUBLIC_KEYCLOAK_ENABLED=true
      - NEXT_PUBLIC_KEYCLOAK_URL=https://stage.aran.me
      - NEXT_PUBLIC_KEYCLOAK_REALM=master
      - NEXT_PUBLIC_KEYCLOAK_CLIENT_ID=ciyex-app

patchesStrategicMerge:
  - deployment-patch.yaml

patches:
  - target:
      kind: HTTPRoute
      name: ciyex-ehr-ui
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: app-stage.ciyex.org
