apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ciyex-ehr-ui
spec:
  parentRefs:
    - name: private-gateway
      namespace: istio-ingress
      sectionName: https
  hostnames:
    - ehr.apps.example.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ciyex-ehr-ui
          port: 3000
