apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: registry.apps-prod.us-east.in.hinisoft.com/ciyex-ehr-ui
    newTag: "0.0.2-alpha.5"

patches:
  - target:
      kind: HTTPRoute
      name: ciyex-ehr-ui
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: ehr.apps-dev.us-east.in.hinisoft.com
